# Copyright (C) 2017 Alpha Griffin
# @%@~LICENSE~@%@
# TF_curses
# /.travis.yml
# __author__ = Ruckusist

language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy3"
    - "nightly"

install:
    # - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install install Twisted; fi
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install coveralls

script:
    - pytest
    # - coverage run --source=tf_curses setup.py test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d51c3b71efc2b8b59d40
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: change
        on_start: never     # options: [always|never|change] default: never

matrix:
    fast_finish: true