# Copyright (C) 2017 Alpha Griffin
# Aether Project
# /.travis.yml
# __author__ = Ruckusist

language: python

python:
    - "3.5"
    - "3.6"
install:
    # - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install install Twisted; fi
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install coveralls

script:
    - coverage run setup.py install

after_success:
    - coveralls
