# Copyright (C) 2017 Alpha Griffin
# TF_curses
# /.travis.yml
# __author__ = Ruckusist

language: python

python:
    - "3.5"
    - "3.6"
install:
    # - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install install Twisted; fi
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install coveralls
    - pip install tox

script:
    - coverage run setup.py install

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d51c3b71efc2b8b59d40
        on_success: always  # options: [always|never|change] default: always
        on_failure: never   # options: [always|never|change] default: change
        on_start: never     # options: [always|never|change] default: never
